apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-service
  name: udagram-api-service
spec:
  type: LoadBalancer
  ports:
  - name: udagram-api-service
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-proxy
